<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="GroupListNet.Addons" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.14" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="Telegram.Bot" Version="22.7.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GroupListNet.Utils\GroupListNet.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\Resources\ErrorCodes\AuthenticationErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AuthenticationErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\AutoTimeTrackErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoTimeTrackErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\BaseErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BaseErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\IssueErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IssueErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\ProjectErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProjectErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\SosErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SosErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\SystemErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SystemErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\UserErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserErrorCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="src\Resources\ErrorCodes\WorkspaceErrorCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WorkspaceErrorCodeResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="src\Resources\ErrorCodes\AuthenticationErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AuthenticationErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\AutoTimeTrackErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AutoTimeTrackErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\BaseErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>BaseErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\IssueErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IssueErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\ProjectErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ProjectErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\SosErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SosErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\SystemErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SystemErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\UserErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UserErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="src\Resources\ErrorCodes\WorkspaceErrorCodeResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WorkspaceErrorCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Models\ResponseModels\" />
  </ItemGroup>

</Project>
