//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupListNet.Core.src.Resources.ErrorCodes {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectErrorCodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectErrorCodeResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupListNet.Core.src.Resources.ErrorCodes.ProjectErrorCodeResources", typeof(ProjectErrorCodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string AuthorNotSet {
            get {
                return ResourceManager.GetString("AuthorNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to verify the current user&apos;s permissions. Please contact support.
        /// </summary>
        internal static string CannotCheckOwner {
            get {
                return ResourceManager.GetString("CannotCheckOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string CannotCreateProject {
            get {
                return ResourceManager.GetString("CannotCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get managers for your workspace. Please contact support.
        /// </summary>
        internal static string CannotGetProjectMgrCandidates {
            get {
                return ResourceManager.GetString("CannotGetProjectMgrCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve project information. Please contact support.
        /// </summary>
        internal static string CannotGetProjects {
            get {
                return ResourceManager.GetString("CannotGetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string EndDateNotSet {
            get {
                return ResourceManager.GetString("EndDateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty code of project.
        /// </summary>
        internal static string ProjectEmptyCode {
            get {
                return ResourceManager.GetString("ProjectEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty name of project.
        /// </summary>
        internal static string ProjectEmptyName {
            get {
                return ResourceManager.GetString("ProjectEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string ProjectMgrNotSet {
            get {
                return ResourceManager.GetString("ProjectMgrNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose another project manager.
        /// </summary>
        internal static string ProjectMgrNotWspMember {
            get {
                return ResourceManager.GetString("ProjectMgrNotWspMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project with the same name exists.
        /// </summary>
        internal static string ProjectWithNameOrCodeExists {
            get {
                return ResourceManager.GetString("ProjectWithNameOrCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start date in future.
        /// </summary>
        internal static string StartDateInFuture {
            get {
                return ResourceManager.GetString("StartDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access to organization projects is restricted. Contact the owner of your organization.
        /// </summary>
        internal static string UserNotMemberWsp {
            get {
                return ResourceManager.GetString("UserNotMemberWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string WorkspaceNotSet {
            get {
                return ResourceManager.GetString("WorkspaceNotSet", resourceCulture);
            }
        }
    }
}
