//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupListNet.Core.src.Resources.ErrorCodes {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkspaceErrorCodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkspaceErrorCodeResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupListNet.Core.src.Resources.ErrorCodes.WorkspaceErrorCodeResources", typeof(WorkspaceErrorCodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user has already been invited to the workspace. The user must confirm the request.
        /// </summary>
        internal static string ActiveInviteAlreadyExists {
            get {
                return ResourceManager.GetString("ActiveInviteAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in the address.
        /// </summary>
        internal static string AddressNull {
            get {
                return ResourceManager.GetString("AddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can only create one personal workspace.
        /// </summary>
        internal static string CanCreateOnlyOnePersonalWorkspace {
            get {
                return ResourceManager.GetString("CanCreateOnlyOnePersonalWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to accept request. Please contact support.
        /// </summary>
        internal static string CannotAcceptInviteWsp {
            get {
                return ResourceManager.GetString("CannotAcceptInviteWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to change workspace status. Please contact support.
        /// </summary>
        internal static string CannotChangeReviewStatus {
            get {
                return ResourceManager.GetString("CannotChangeReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create workspace invite.
        /// </summary>
        internal static string CannotCreateOrEditInviteWsp {
            get {
                return ResourceManager.GetString("CannotCreateOrEditInviteWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not create or modify workspace. Please contact support.
        /// </summary>
        internal static string CannotCreateOrEditWorkspace {
            get {
                return ResourceManager.GetString("CannotCreateOrEditWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to find any users. Please contact support.
        /// </summary>
        internal static string CannotFindUserForInvite {
            get {
                return ResourceManager.GetString("CannotFindUserForInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve information about available workspaces. Please, contact to support..
        /// </summary>
        internal static string CannotGetMyWorkspaces {
            get {
                return ResourceManager.GetString("CannotGetMyWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve workspace invitation information.
        /// </summary>
        internal static string CannotGetWpsRequests {
            get {
                return ResourceManager.GetString("CannotGetWpsRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve workspace information for verification. Please contact support.
        /// </summary>
        internal static string CannotGetWspForAdmin {
            get {
                return ResourceManager.GetString("CannotGetWspForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A company with the same parameters exists (country, registration date, registration address)..
        /// </summary>
        internal static string CompanyWithDataAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyWithDataAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A company with this tax ID already exists.
        /// </summary>
        internal static string CompanyWithInnAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyWithInnAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A company with that name already exists.
        /// </summary>
        internal static string CompanyWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in the country value.
        /// </summary>
        internal static string CountryNull {
            get {
                return ResourceManager.GetString("CountryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in the tax identification number.
        /// </summary>
        internal static string INNNull {
            get {
                return ResourceManager.GetString("INNNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string InvalidStatusInvite {
            get {
                return ResourceManager.GetString("InvalidStatusInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing request. Please contact support.
        /// </summary>
        internal static string InviteIdNotSet {
            get {
                return ResourceManager.GetString("InviteIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This invite does not exist. Please contact support.
        /// </summary>
        internal static string InviteNotExists {
            get {
                return ResourceManager.GetString("InviteNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in the registration date.
        /// </summary>
        internal static string RegistrationDateNull {
            get {
                return ResourceManager.GetString("RegistrationDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System error: invalid review status. Please contact support.
        /// </summary>
        internal static string ReviewStatusInvalid {
            get {
                return ResourceManager.GetString("ReviewStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System error: review status not set. Please contact support.
        /// </summary>
        internal static string ReviewStatusNotSet {
            get {
                return ResourceManager.GetString("ReviewStatusNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System error. Please contact technical support.
        /// </summary>
        internal static string ReviewStatusNull {
            get {
                return ResourceManager.GetString("ReviewStatusNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System error. Please refresh the page and try again. If unsuccessful, contact technical support.
        /// </summary>
        internal static string ReviewStatusWrong {
            get {
                return ResourceManager.GetString("ReviewStatusWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user is already in this workspace.
        /// </summary>
        internal static string UserAlreadyInWsp {
            get {
                return ResourceManager.GetString("UserAlreadyInWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User not found in such workspace.
        /// </summary>
        internal static string UserNotFoundInWsp {
            get {
                return ResourceManager.GetString("UserNotFoundInWsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System error: workspace not found. Please contact support.
        /// </summary>
        internal static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating request. Please contact support.
        /// </summary>
        internal static string WorkspaceNotSet {
            get {
                return ResourceManager.GetString("WorkspaceNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating request. Please contact support.
        /// </summary>
        internal static string WpsForInviteNotExists {
            get {
                return ResourceManager.GetString("WpsForInviteNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating request. Please contact support.
        /// </summary>
        internal static string WpsInviteReqDateFuture {
            get {
                return ResourceManager.GetString("WpsInviteReqDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating request. Please contact support.
        /// </summary>
        internal static string WpsInviteReqDateNotSet {
            get {
                return ResourceManager.GetString("WpsInviteReqDateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating request. Please contact support.
        /// </summary>
        internal static string WpsInviterIdNotSet {
            get {
                return ResourceManager.GetString("WpsInviterIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user is incorrect. Please try again or contact support.
        /// </summary>
        internal static string WpsInviteUserIdNotSet {
            get {
                return ResourceManager.GetString("WpsInviteUserIdNotSet", resourceCulture);
            }
        }
    }
}
